# This is a workflow to help you test your code
name: Test

on:
  push:
    branches: [ "shz_dev", "binci_dev" ]
  pull_request:
    branches: [ "master", "main" ]

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run code test
        run: |
          bash test.sh
          echo "Finish test"
          echo "You can merge this pull request"
